import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding ScoutDeck baseball database...");

  // Clean existing data
  await prisma.scoutingReport.deleteMany();
  await prisma.prospect.deleteMany();

  const prospects = [
    {
      name: "Ethan 'Jax' Mercer",
      position: "SS",
      secondaryPosition: "3B",
      bats: "L",
      throws: "R",
      height: "6'3\"",
      weight: 205,
      school: "Corona High School (CA)",
      schoolType: "HIGH_SCHOOL",
      gradYear: 2025,
      status: "TOP_TARGET",
      commitment: "LSU",
      draftProjection: "Top 5 Overall Pick",
      proComp: "Corey Seager / Gunnar Henderson",
      summary: "Generational high school shortstop with elite frame, effortless plus raw power to all fields, and fluid instincts on defense. High baseball IQ with clean swing decisions.",
      tags: "5-Tool Potential, Plus Raw Power, Left-Handed Slugger, High IQ",
      exitVelocityMax: 108.4,
      sixtyTime: 6.55,
      popTime: null,
      fastballVeloPeak: null,
      fastballVeloSit: null,
      spinRate: null,
      hitPresent: 45,
      hitFuture: 65,
      powerPresent: 40,
      powerFuture: 70,
      runPresent: 60,
      runFuture: 55,
      armPresent: 55,
      armFuture: 65,
      fieldPresent: 50,
      fieldFuture: 60,
      ofpScore: 65,
      reports: {
        create: [
          {
            scoutName: "Mike Callahan (West Coast Crosschecker)",
            eventName: "Area Code Games (Long Beach, CA)",
            summary: "Dominated tournament pitching. Barrel stayed in the zone for an eternity; crushed a 94 mph fastball 415 feet off the batter's eye. Moves laterally with soft hands and plus arm carry across the diamond.",
            strengths: "Bat speed, barrel control, projectable frame, arm strength, calm demeanor",
            weaknesses: "May outgrow shortstop long-term as physical strength fills out, potentially sliding to third base",
            videoUrl: "https://www.youtube.com/watch?v=sample1",
            grade: 65,
          },
          {
            scoutName: "David Vance (National Scouting Director)",
            eventName: "PG National Showcase",
            summary: "Recorded 108.4 mph max exit velo during BP. Showed impressive two-strike approach against elite velocity in live gameplay. High-character clubhouse leader.",
            strengths: "Elite plate discipline, zone awareness, clutch situational hitting",
            weaknesses: "Slight swing-and-miss against elevated sweepers with late horizontal break",
            videoUrl: null,
            grade: 65,
          },
        ],
      },
    },
    {
      name: "Cole 'The Missile' Braddock",
      position: "RHP",
      secondaryPosition: null,
      bats: "R",
      throws: "R",
      height: "6'6\"",
      weight: 230,
      school: "Vanderbilt University",
      schoolType: "COLLEGE",
      gradYear: 2025,
      status: "TOP_TARGET",
      commitment: "Draft Eligible Sophomore",
      draftProjection: "Top 3 Overall Pick",
      proComp: "Paul Skenes / Gerrit Cole",
      summary: "Intimidating collegiate ace with an electric four-pitch mix. Fastball routinely touches triple digits with exceptional ride at the top of the strike zone. Wipeout sweeper that generates over 45% whiff rates.",
      tags: "Triple-Digit Fastball, Power Pitcher, Wipeout Slider, Friday Night Starter",
      exitVelocityMax: null,
      sixtyTime: null,
      popTime: null,
      fastballVeloPeak: 101.8,
      fastballVeloSit: 97.5,
      spinRate: 2620,
      hitPresent: 20,
      hitFuture: 20,
      powerPresent: 20,
      powerFuture: 20,
      runPresent: 30,
      runFuture: 30,
      armPresent: 80,
      armFuture: 80,
      fieldPresent: 50,
      fieldFuture: 55,
      fastballPresent: 70,
      fastballFuture: 80,
      sliderPresent: 60,
      sliderFuture: 70,
      curveballPresent: 50,
      curveballFuture: 55,
      changeupPresent: 45,
      changeupFuture: 60,
      commandPresent: 55,
      commandFuture: 65,
      ofpScore: 70,
      reports: {
        create: [
          {
            scoutName: "David Vance (National Scouting Director)",
            eventName: "SEC Tournament vs. Tennessee",
            summary: "Pitched 7.2 innings, allowed 1 hit, struck out 13. Fastball sat 97-99 mph through the 7th inning. Sweeper at 86-88 mph with 18 inches of horizontal break left SEC hitters completely off balance.",
            strengths: "Elite velocity, stamina, mound presence, repeatable high-3/4 delivery",
            weaknesses: "Can fall in love with the fastball when ahead in the count; changeup is still developing consistency",
            videoUrl: "https://www.youtube.com/watch?v=sample2",
            grade: 70,
          },
        ],
      },
    },
    {
      name: "Lucas Alcantara",
      position: "CF",
      secondaryPosition: "LF",
      bats: "R",
      throws: "R",
      height: "6'1\"",
      weight: 185,
      school: "Archbishop McCarthy HS (FL)",
      schoolType: "HIGH_SCHOOL",
      gradYear: 2025,
      status: "OFFERED",
      commitment: "Florida State",
      draftProjection: "Round 1 (Pick 15-25)",
      proComp: "Ceddanne Rafaela / Byron Buxton lite",
      summary: "80-grade runner with game-changing centerfield defense and pure gap-to-gap speed. Blazing 6.38 60-yard dash. Creates havoc on the basepaths and tracks down extra-base hits in both gaps effortlessly.",
      tags: "80-Grade Speed, Gold Glove Instincts, Baserunning Threat, High Energy",
      exitVelocityMax: 101.2,
      sixtyTime: 6.38,
      popTime: null,
      fastballVeloPeak: null,
      fastballVeloSit: null,
      spinRate: null,
      hitPresent: 40,
      hitFuture: 55,
      powerPresent: 30,
      powerFuture: 45,
      runPresent: 80,
      runFuture: 80,
      armPresent: 55,
      armFuture: 60,
      fieldPresent: 65,
      fieldFuture: 75,
      ofpScore: 60,
      reports: {
        create: [
          {
            scoutName: "Sam Rodriguez (Southeast Regional)",
            eventName: "WWBA World Championship (Jupiter, FL)",
            summary: "The fastest player on any diamond this week. Recorded two bunt singles at 3.75s home-to-first. Robbed a 3-run homer with a leaping grab at the wall. High energy, game-disruptor profile.",
            strengths: "Blistering top-end speed, elite jump on fly balls, premium centerfield defense",
            weaknesses: "Needs to add strength to hold up against inside fastballs at pro level; groundball-heavy launch angle",
            videoUrl: null,
            grade: 60,
          },
        ],
      },
    },
    {
      name: "Mateo 'The Wall' Cruz",
      position: "C",
      secondaryPosition: "1B",
      bats: "R",
      throws: "R",
      height: "6'2\"",
      weight: 215,
      school: "Texas A&M University",
      schoolType: "COLLEGE",
      gradYear: 2025,
      status: "TOP_TARGET",
      commitment: "Draft Eligible Junior",
      draftProjection: "Late 1st Round / Early 2nd Round",
      proComp: "Will Smith (LAD) / Cal Raleigh",
      summary: "Premier defensive backstop with an electric 1.83s pop time, rock-solid framing metrics, and genuine 25+ home run power potential. Highly respected for his pitch-calling and handling of power arms.",
      tags: "Sub-1.85 Pop Time, Plus Game Power, Defensive Anchor, Pitch Framing",
      exitVelocityMax: 106.1,
      sixtyTime: 7.25,
      popTime: 1.83,
      fastballVeloPeak: null,
      fastballVeloSit: null,
      spinRate: null,
      hitPresent: 45,
      hitFuture: 50,
      powerPresent: 55,
      powerFuture: 65,
      runPresent: 30,
      runFuture: 30,
      armPresent: 65,
      armFuture: 70,
      fieldPresent: 60,
      fieldFuture: 65,
      ofpScore: 55,
      reports: {
        create: [
          {
            scoutName: "Mike Callahan (Crosschecker)",
            eventName: "College World Series (Omaha)",
            summary: "Threw out 3 runners in 4 attempts during the regional and super regional. Gun arm with laser accuracy to second base. Pulled two tape-measure home runs to left field. Built like a brick wall behind the dish.",
            strengths: "Cannon arm, low target setup, framing, pull-side power",
            weaknesses: "Below average runner; some swing-and-miss against quality back-foot breaking balls",
            videoUrl: null,
            grade: 55,
          },
        ],
      },
    },
    {
      name: "Nico Hernandez",
      position: "LHP",
      secondaryPosition: null,
      bats: "L",
      throws: "L",
      height: "6'4\"",
      weight: 210,
      school: "St. Thomas Aquinas HS (FL)",
      schoolType: "HIGH_SCHOOL",
      gradYear: 2025,
      status: "OFFERED",
      commitment: "Wake Forest",
      draftProjection: "Round 1 (Pick 10-20)",
      proComp: "Cole Ragans / Blake Snell",
      summary: "Lanky southpaw with deceptive, low-effort arm action. Fastball shows late arm-side run, paired with an 84 mph power slurve and a fading circle changeup that completely neutralizes right-handed bats.",
      tags: "Power Southpaw, High Deception, Plus Changeup, Low-Effort Delivery",
      exitVelocityMax: null,
      sixtyTime: null,
      popTime: null,
      fastballVeloPeak: 96.7,
      fastballVeloSit: 92.5,
      spinRate: 2480,
      hitPresent: 20,
      hitFuture: 20,
      powerPresent: 20,
      powerFuture: 20,
      runPresent: 45,
      runFuture: 45,
      armPresent: 70,
      armFuture: 75,
      fieldPresent: 50,
      fieldFuture: 55,
      fastballPresent: 55,
      fastballFuture: 65,
      sliderPresent: 55,
      sliderFuture: 65,
      curveballPresent: 50,
      curveballFuture: 60,
      changeupPresent: 60,
      changeupFuture: 70,
      commandPresent: 50,
      commandFuture: 60,
      ofpScore: 60,
      reports: {
        create: [
          {
            scoutName: "Sam Rodriguez (Southeast Regional)",
            eventName: "National High School Invitational",
            summary: "Complete game shutout with 14 strikeouts. Fastball sat 92-95 mph with tremendous sink and arm-side run. Changeup generated 11 whiffs on 14 swings. Easy velocity with clean mechanics.",
            strengths: "Three-pitch mix for strikes, plus changeup, athletic frame, projectable velocity",
            weaknesses: "Needs to maintain arm slot when working out of the stretch with runners on base",
            videoUrl: null,
            grade: 60,
          },
        ],
      },
    },
    {
      name: "Julian 'The Hammer' Vance",
      position: "3B",
      secondaryPosition: "1B",
      bats: "R",
      throws: "R",
      height: "6'4\"",
      weight: 225,
      school: "University of Tennessee",
      schoolType: "COLLEGE",
      gradYear: 2025,
      status: "WATCHLIST",
      commitment: "Draft Eligible Junior",
      draftProjection: "Round 1 Comp / Round 2",
      proComp: "Austin Riley / Nolan Arenado lite",
      summary: "Pure corner power bat who led the nation in barrels and average exit velocity (94.2 mph). Quick hands through the zone, elite durability, and surprising reaction time at third base.",
      tags: "70-Grade Raw Power, Exit Velocity Monster, Big League Frame, Strong Arm",
      exitVelocityMax: 112.3,
      sixtyTime: 7.10,
      popTime: null,
      fastballVeloPeak: null,
      fastballVeloSit: null,
      spinRate: null,
      hitPresent: 45,
      hitFuture: 50,
      powerPresent: 65,
      powerFuture: 75,
      runPresent: 35,
      runFuture: 35,
      armPresent: 60,
      armFuture: 65,
      fieldPresent: 50,
      fieldFuture: 55,
      ofpScore: 55,
      reports: {
        create: [
          {
            scoutName: "Mike Callahan (Crosschecker)",
            eventName: "Cape Cod Baseball League",
            summary: "Led the Cape in home runs with wood bats. Handled 97+ mph velo without expanding the strike zone. Defense at third is solid, with a strong, accurate arm across the diamond.",
            strengths: "Top-tier exit velo, monstrous raw power, durable frame, strong arm",
            weaknesses: "Limited lateral range; will need to monitor weight as he enters pro ball",
            videoUrl: null,
            grade: 55,
          },
        ],
      },
    },
    {
      name: "Brody Albright",
      position: "OF",
      secondaryPosition: "CF",
      bats: "L",
      throws: "L",
      height: "6'2\"",
      weight: 195,
      school: "Southlake Carroll HS (TX)",
      schoolType: "HIGH_SCHOOL",
      gradYear: 2026,
      status: "WATCHLIST",
      commitment: "Texas",
      draftProjection: "2026 1st Round Prospect",
      proComp: "Kyle Tucker / Christian Yelich",
      summary: "High-ceiling underclassman with one of the purest left-handed swings in amateur baseball. Exceptional barrel control, natural loft, and plus instincts on both sides of the ball.",
      tags: "Pure Left-Handed Stroke, Underclass Standout, Projectable Power, High Floor",
      exitVelocityMax: 104.5,
      sixtyTime: 6.65,
      popTime: null,
      fastballVeloPeak: null,
      fastballVeloSit: null,
      spinRate: null,
      hitPresent: 40,
      hitFuture: 65,
      powerPresent: 35,
      powerFuture: 60,
      runPresent: 55,
      runFuture: 60,
      armPresent: 50,
      armFuture: 55,
      fieldPresent: 50,
      fieldFuture: 60,
      ofpScore: 60,
      reports: {
        create: [
          {
            scoutName: "David Vance (National Scouting Director)",
            eventName: "Under Armour All-America Game",
            summary: "Showed supreme poise against senior pitching. Fluid two-piece swing with lightning-fast hips. Hit two doubles into the right-center gap. One of the top overall players in the 2026 prep class.",
            strengths: "Swing path, balance, plate coverage, projectable frame",
            weaknesses: "Still physically lean; power output will spike once he adds 15-20 lbs of muscle",
            videoUrl: null,
            grade: 60,
          },
        ],
      },
    },
  ];

  for (const prospectData of prospects) {
    const p = await prisma.prospect.create({
      data: prospectData,
    });
    console.log(`Created prospect: ${p.name} (${p.position}) - OFP: ${p.ofpScore}`);
  }

  console.log("Database successfully seeded with realistic baseball prospects!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
