import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding ScoutDeck baseball database with expanded prospect roster...");

  // Clean existing data
  await prisma.scoutingReport.deleteMany();
  await prisma.prospect.deleteMany();

  const prospects = [
    {
      name: "Ethan 'Jax' Mercer",
      position: "SS",
      secondaryPosition: "3B",
      bats: "L",
      throws: "R",
      height: "6'3\"",
      weight: 205,
      school: "Corona High School (CA)",
      schoolType: "HIGH_SCHOOL",
      gradYear: 2025,
      status: "TOP_TARGET",
      commitment: "LSU",
      draftProjection: "Top 5 Overall Pick",
      proComp: "Corey Seager / Gunnar Henderson",
      summary: "Generational high school shortstop with elite frame, effortless plus raw power to all fields, and fluid instincts on defense. High baseball IQ with clean swing decisions.",
      tags: "5-Tool Potential, Plus Raw Power, Left-Handed Slugger, High IQ",
      exitVelocityMax: 108.4,
      sixtyTime: 6.55,
      popTime: null,
      fastballVeloPeak: null,
      fastballVeloSit: null,
      spinRate: null,
      hitPresent: 45,
      hitFuture: 65,
      powerPresent: 40,
      powerFuture: 70,
      runPresent: 60,
      runFuture: 55,
      armPresent: 55,
      armFuture: 65,
      fieldPresent: 50,
      fieldFuture: 60,
      ofpScore: 65,
      reports: {
        create: [
          {
            scoutName: "Mike Callahan (West Coast Crosschecker)",
            eventName: "Area Code Games (Long Beach, CA)",
            summary: "Dominated tournament pitching. Barrel stayed in the zone for an eternity; crushed a 94 mph fastball 415 feet off the batter's eye. Moves laterally with soft hands and plus arm carry across the diamond.",
            strengths: "Bat speed, barrel control, projectable frame, arm strength, calm demeanor",
            weaknesses: "May outgrow shortstop long-term as physical strength fills out, potentially sliding to third base",
            videoUrl: "https://www.youtube.com/watch?v=sample1",
            grade: 65,
          },
          {
            scoutName: "David Vance (National Scouting Director)",
            eventName: "PG National Showcase",
            summary: "Recorded 108.4 mph max exit velo during BP. Showed impressive two-strike approach against elite velocity in live gameplay. High-character clubhouse leader.",
            strengths: "Elite plate discipline, zone awareness, clutch situational hitting",
            weaknesses: "Slight swing-and-miss against elevated sweepers with late horizontal break",
            videoUrl: null,
            grade: 65,
          },
        ],
      },
    },
    {
      name: "Cole 'The Missile' Braddock",
      position: "RHP",
      secondaryPosition: null,
      bats: "R",
      throws: "R",
      height: "6'6\"",
      weight: 230,
      school: "Vanderbilt University",
      schoolType: "COLLEGE",
      gradYear: 2025,
      status: "TOP_TARGET",
      commitment: "Draft Eligible Sophomore",
      draftProjection: "Top 3 Overall Pick",
      proComp: "Paul Skenes / Gerrit Cole",
      summary: "Intimidating collegiate ace with an electric four-pitch mix. Fastball routinely touches triple digits with exceptional ride at the top of the strike zone. Wipeout sweeper that generates over 45% whiff rates.",
      tags: "Triple-Digit Fastball, Power Pitcher, Wipeout Slider, Friday Night Starter",
      exitVelocityMax: null,
      sixtyTime: null,
      popTime: null,
      fastballVeloPeak: 101.8,
      fastballVeloSit: 97.5,
      spinRate: 2620,
      hitPresent: 20,
      hitFuture: 20,
      powerPresent: 20,
      powerFuture: 20,
      runPresent: 30,
      runFuture: 30,
      armPresent: 80,
      armFuture: 80,
      fieldPresent: 50,
      fieldFuture: 55,
      fastballPresent: 70,
      fastballFuture: 80,
      sliderPresent: 60,
      sliderFuture: 70,
      curveballPresent: 50,
      curveballFuture: 55,
      changeupPresent: 45,
      changeupFuture: 60,
      commandPresent: 55,
      commandFuture: 65,
      ofpScore: 70,
      reports: {
        create: [
          {
            scoutName: "David Vance (National Scouting Director)",
            eventName: "SEC Tournament vs. Tennessee",
            summary: "Pitched 7.2 innings, allowed 1 hit, struck out 13. Fastball sat 97-99 mph through the 7th inning. Sweeper at 86-88 mph with 18 inches of horizontal break left SEC hitters completely off balance.",
            strengths: "Elite velocity, stamina, mound presence, repeatable high-3/4 delivery",
            weaknesses: "Can fall in love with the fastball when ahead in the count; changeup is still developing consistency",
            videoUrl: "https://www.youtube.com/watch?v=sample2",
            grade: 70,
          },
        ],
      },
    },
    {
      name: "Lucas Alcantara",
      position: "CF",
      secondaryPosition: "LF",
      bats: "R",
      throws: "R",
      height: "6'1\"",
      weight: 185,
      school: "Archbishop McCarthy HS (FL)",
      schoolType: "HIGH_SCHOOL",
      gradYear: 2025,
      status: "OFFERED",
      commitment: "Florida State",
      draftProjection: "Round 1 (Pick 15-25)",
      proComp: "Ceddanne Rafaela / Byron Buxton lite",
      summary: "80-grade runner with game-changing centerfield defense and pure gap-to-gap speed. Blazing 6.38 60-yard dash. Creates havoc on the basepaths and tracks down extra-base hits in both gaps effortlessly.",
      tags: "80-Grade Speed, Gold Glove Instincts, Baserunning Threat, High Energy",
      exitVelocityMax: 101.2,
      sixtyTime: 6.38,
      popTime: null,
      fastballVeloPeak: null,
      fastballVeloSit: null,
      spinRate: null,
      hitPresent: 40,
      hitFuture: 55,
      powerPresent: 30,
      powerFuture: 45,
      runPresent: 80,
      runFuture: 80,
      armPresent: 55,
      armFuture: 60,
      fieldPresent: 65,
      fieldFuture: 75,
      ofpScore: 60,
      reports: {
        create: [
          {
            scoutName: "Sam Rodriguez (Southeast Regional)",
            eventName: "WWBA World Championship (Jupiter, FL)",
            summary: "The fastest player on any diamond this week. Recorded two bunt singles at 3.75s home-to-first. Robbed a 3-run homer with a leaping grab at the wall. High energy, game-disruptor profile.",
            strengths: "Blistering top-end speed, elite jump on fly balls, premium centerfield defense",
            weaknesses: "Needs to add strength to hold up against inside fastballs at pro level; groundball-heavy launch angle",
            videoUrl: null,
            grade: 60,
          },
        ],
      },
    },
    {
      name: "Mateo 'The Wall' Cruz",
      position: "C",
      secondaryPosition: "1B",
      bats: "R",
      throws: "R",
      height: "6'2\"",
      weight: 215,
      school: "Texas A&M University",
      schoolType: "COLLEGE",
      gradYear: 2025,
      status: "TOP_TARGET",
      commitment: "Draft Eligible Junior",
      draftProjection: "Late 1st Round / Early 2nd Round",
      proComp: "Will Smith (LAD) / Cal Raleigh",
      summary: "Premier defensive backstop with an electric 1.83s pop time, rock-solid framing metrics, and genuine 25+ home run power potential. Highly respected for his pitch-calling and handling of power arms.",
      tags: "Sub-1.85 Pop Time, Plus Game Power, Defensive Anchor, Pitch Framing",
      exitVelocityMax: 106.1,
      sixtyTime: 7.25,
      popTime: 1.83,
      fastballVeloPeak: null,
      fastballVeloSit: null,
      spinRate: null,
      hitPresent: 45,
      hitFuture: 50,
      powerPresent: 55,
      powerFuture: 65,
      runPresent: 30,
      runFuture: 30,
      armPresent: 65,
      armFuture: 70,
      fieldPresent: 60,
      fieldFuture: 65,
      ofpScore: 55,
      reports: {
        create: [
          {
            scoutName: "Mike Callahan (Crosschecker)",
            eventName: "College World Series (Omaha)",
            summary: "Threw out 3 runners in 4 attempts during the regional and super regional. Gun arm with laser accuracy to second base. Pulled two tape-measure home runs to left field. Built like a brick wall behind the dish.",
            strengths: "Cannon arm, low target setup, framing, pull-side power",
            weaknesses: "Below average runner; some swing-and-miss against quality back-foot breaking balls",
            videoUrl: null,
            grade: 55,
          },
        ],
      },
    },
    {
      name: "Nico Hernandez",
      position: "LHP",
      secondaryPosition: null,
      bats: "L",
      throws: "L",
      height: "6'4\"",
      weight: 210,
      school: "St. Thomas Aquinas HS (FL)",
      schoolType: "HIGH_SCHOOL",
      gradYear: 2025,
      status: "OFFERED",
      commitment: "Wake Forest",
      draftProjection: "Round 1 (Pick 10-20)",
      proComp: "Cole Ragans / Blake Snell",
      summary: "Lanky southpaw with deceptive, low-effort arm action. Fastball shows late arm-side run, paired with an 84 mph power slurve and a fading circle changeup that completely neutralizes right-handed bats.",
      tags: "Power Southpaw, High Deception, Plus Changeup, Low-Effort Delivery",
      exitVelocityMax: null,
      sixtyTime: null,
      popTime: null,
      fastballVeloPeak: 96.7,
      fastballVeloSit: 92.5,
      spinRate: 2480,
      hitPresent: 20,
      hitFuture: 20,
      powerPresent: 20,
      powerFuture: 20,
      runPresent: 45,
      runFuture: 45,
      armPresent: 70,
      armFuture: 75,
      fieldPresent: 50,
      fieldFuture: 55,
      fastballPresent: 55,
      fastballFuture: 65,
      sliderPresent: 55,
      sliderFuture: 65,
      curveballPresent: 50,
      curveballFuture: 60,
      changeupPresent: 60,
      changeupFuture: 70,
      commandPresent: 50,
      commandFuture: 60,
      ofpScore: 60,
      reports: {
        create: [
          {
            scoutName: "Sam Rodriguez (Southeast Regional)",
            eventName: "National High School Invitational",
            summary: "Complete game shutout with 14 strikeouts. Fastball sat 92-95 mph with tremendous sink and arm-side run. Changeup generated 11 whiffs on 14 swings. Easy velocity with clean mechanics.",
            strengths: "Three-pitch mix for strikes, plus changeup, athletic frame, projectable velocity",
            weaknesses: "Needs to maintain arm slot when working out of the stretch with runners on base",
            videoUrl: null,
            grade: 60,
          },
        ],
      },
    },
    {
      name: "Julian 'The Hammer' Vance",
      position: "3B",
      secondaryPosition: "1B",
      bats: "R",
      throws: "R",
      height: "6'4\"",
      weight: 225,
      school: "University of Tennessee",
      schoolType: "COLLEGE",
      gradYear: 2025,
      status: "WATCHLIST",
      commitment: "Draft Eligible Junior",
      draftProjection: "Round 1 Comp / Round 2",
      proComp: "Austin Riley / Nolan Arenado lite",
      summary: "Pure corner power bat who led the nation in barrels and average exit velocity (94.2 mph). Quick hands through the zone, elite durability, and surprising reaction time at third base.",
      tags: "70-Grade Raw Power, Exit Velocity Monster, Big League Frame, Strong Arm",
      exitVelocityMax: 112.3,
      sixtyTime: 7.10,
      popTime: null,
      fastballVeloPeak: null,
      fastballVeloSit: null,
      spinRate: null,
      hitPresent: 45,
      hitFuture: 50,
      powerPresent: 65,
      powerFuture: 75,
      runPresent: 35,
      runFuture: 35,
      armPresent: 60,
      armFuture: 65,
      fieldPresent: 50,
      fieldFuture: 55,
      ofpScore: 55,
      reports: {
        create: [
          {
            scoutName: "Mike Callahan (Crosschecker)",
            eventName: "Cape Cod Baseball League",
            summary: "Led the Cape in home runs with wood bats. Handled 97+ mph velo without expanding the strike zone. Defense at third is solid, with a strong, accurate arm across the diamond.",
            strengths: "Top-tier exit velo, monstrous raw power, durable frame, strong arm",
            weaknesses: "Limited lateral range; will need to monitor weight as he enters pro ball",
            videoUrl: null,
            grade: 55,
          },
        ],
      },
    },
    {
      name: "Brody Albright",
      position: "OF",
      secondaryPosition: "CF",
      bats: "L",
      throws: "L",
      height: "6'2\"",
      weight: 195,
      school: "Southlake Carroll HS (TX)",
      schoolType: "HIGH_SCHOOL",
      gradYear: 2026,
      status: "WATCHLIST",
      commitment: "Texas",
      draftProjection: "2026 1st Round Prospect",
      proComp: "Kyle Tucker / Christian Yelich",
      summary: "High-ceiling underclassman with one of the purest left-handed swings in amateur baseball. Exceptional barrel control, natural loft, and plus instincts on both sides of the ball.",
      tags: "Pure Left-Handed Stroke, Underclass Standout, Projectable Power, High Floor",
      exitVelocityMax: 104.5,
      sixtyTime: 6.65,
      popTime: null,
      fastballVeloPeak: null,
      fastballVeloSit: null,
      spinRate: null,
      hitPresent: 40,
      hitFuture: 65,
      powerPresent: 35,
      powerFuture: 60,
      runPresent: 55,
      runFuture: 60,
      armPresent: 50,
      armFuture: 55,
      fieldPresent: 50,
      fieldFuture: 60,
      ofpScore: 60,
      reports: {
        create: [
          {
            scoutName: "David Vance (National Scouting Director)",
            eventName: "Under Armour All-America Game",
            summary: "Showed supreme poise against senior pitching. Fluid two-piece swing with lightning-fast hips. Hit two doubles into the right-center gap. One of the top overall players in the 2026 prep class.",
            strengths: "Swing path, balance, plate coverage, projectable frame",
            weaknesses: "Still physically lean; power output will spike once he adds 15-20 lbs of muscle",
            videoUrl: null,
            grade: 60,
          },
        ],
      },
    },

    // --- NEW EXPANDED PROSPECTS FOR TESTING ---

    {
      name: "Dante 'The Wizard' Morales",
      position: "2B",
      secondaryPosition: "SS",
      bats: "L",
      throws: "R",
      height: "5'11\"",
      weight: 180,
      school: "Wake Forest University",
      schoolType: "COLLEGE",
      gradYear: 2025,
      status: "TOP_TARGET",
      commitment: "Draft Eligible Junior",
      draftProjection: "Round 1 (Pick 12-22)",
      proComp: "Luis Arraez / Nico Hoerner",
      summary: "The preeminent pure contact hitter in college baseball. Possesses uncanny bat-to-ball skill with an 8% whiff rate against 95+ mph velocity. Rarely strikes out, works counts, and sprays line drives from pole to pole.",
      tags: "70 Hit Tool, Elite Zone Awareness, Low Whiff Rate, Gold Glove 2B",
      exitVelocityMax: 103.8,
      sixtyTime: 6.62,
      popTime: null,
      fastballVeloPeak: null,
      fastballVeloSit: null,
      spinRate: null,
      hitPresent: 60,
      hitFuture: 70,
      powerPresent: 35,
      powerFuture: 45,
      runPresent: 60,
      runFuture: 55,
      armPresent: 50,
      armFuture: 50,
      fieldPresent: 60,
      fieldFuture: 65,
      ofpScore: 60,
      reports: {
        create: [
          {
            scoutName: "Greg Holbrook (Atlantic Coast Scout)",
            eventName: "ACC Tournament vs. Virginia",
            summary: "4-for-5 with three opposite-field singles and a double in the gap. Put every ball in play against high-spin collegiate arms. Footwork around the second base bag is effortless.",
            strengths: "Bat control, strike zone discipline, hand-eye coordination, baseball instincts",
            weaknesses: "Below-average raw power; limited extra-base pop beyond gap doubles",
            videoUrl: null,
            grade: 60,
          },
        ],
      },
    },
    {
      name: "Caden 'Thor' Sterling",
      position: "1B",
      secondaryPosition: "DH",
      bats: "R",
      throws: "R",
      height: "6'5\"",
      weight: 245,
      school: "University of Florida",
      schoolType: "COLLEGE",
      gradYear: 2025,
      status: "OFFERED",
      commitment: "Draft Eligible Junior",
      draftProjection: "Late 1st / Early 2nd Round",
      proComp: "Pete Alonso / Triston Casas",
      summary: "Massive middle-of-the-order slugger who produces breathtaking exit velocities (114.8 mph max). Crushes fastballs in any quadrant and creates tape-measure home runs that leave stadiums.",
      tags: "75 Raw Power, Light-Tower Power, 114+ Max EV, Middle-Order Slugger",
      exitVelocityMax: 114.8,
      sixtyTime: 7.35,
      popTime: null,
      fastballVeloPeak: null,
      fastballVeloSit: null,
      spinRate: null,
      hitPresent: 40,
      hitFuture: 50,
      powerPresent: 70,
      powerFuture: 75,
      runPresent: 30,
      runFuture: 30,
      armPresent: 50,
      armFuture: 50,
      fieldPresent: 45,
      fieldFuture: 50,
      ofpScore: 55,
      reports: {
        create: [
          {
            scoutName: "David Vance (National Scouting Director)",
            eventName: "SEC Championship Series",
            summary: "Hit three home runs in three games. One blast measured at 458 feet with a 112 mph exit velo. True 75-grade raw power that will translate to 30+ MLB home runs.",
            strengths: "Elite raw and game power, intimidating presence, strong wrists",
            weaknesses: "High strikeout totals on chase pitches out of the zone; strictly limited to 1B/DH defensively",
            videoUrl: null,
            grade: 55,
          },
        ],
      },
    },
    {
      name: "Kash 'Lightning' Bennett",
      position: "CF",
      secondaryPosition: "OF",
      bats: "S",
      throws: "R",
      height: "6'0\"",
      weight: 175,
      school: "IMG Academy (FL)",
      schoolType: "HIGH_SCHOOL",
      gradYear: 2026,
      status: "WATCHLIST",
      commitment: "Vanderbilt",
      draftProjection: "2026 Top 15 Pick",
      proComp: "Corbin Carroll / Elly De La Cruz speed",
      summary: "Blistering top-of-the-order switch hitter with true 80-grade foot speed. Clocked an astonishing 6.28 60-yard dash at the Perfect Game combine. Elite centerfield range and high-octane basestealing threat.",
      tags: "80 Speed, Switch Hitter, Sub-6.30 60yd, Dynamic Leadoff",
      exitVelocityMax: 102.1,
      sixtyTime: 6.28,
      popTime: null,
      fastballVeloPeak: null,
      fastballVeloSit: null,
      spinRate: null,
      hitPresent: 45,
      hitFuture: 60,
      powerPresent: 30,
      powerFuture: 45,
      runPresent: 80,
      runFuture: 80,
      armPresent: 55,
      armFuture: 60,
      fieldPresent: 60,
      fieldFuture: 70,
      ofpScore: 60,
      reports: {
        create: [
          {
            scoutName: "Sam Rodriguez (Southeast Regional)",
            eventName: "National High School Invitational (Cary, NC)",
            summary: "Stole 6 bases in 3 games. First step acceleration is world-class. Switch hitting stroke is balanced from both sides with line-drive spray charts.",
            strengths: "Pure 80-grade speed, leadoff instincts, centerfield reads, switch-hitter versatility",
            weaknesses: "Slender frame will need core strength to sustain 162-game professional grinds",
            videoUrl: null,
            grade: 60,
          },
        ],
      },
    },
    {
      name: "Zackary 'The Surgeon' Chen",
      position: "RHP",
      secondaryPosition: null,
      bats: "R",
      throws: "R",
      height: "6'3\"",
      weight: 200,
      school: "Oregon State University",
      schoolType: "COLLEGE",
      gradYear: 2025,
      status: "TOP_TARGET",
      commitment: "Draft Eligible Junior",
      draftProjection: "Round 1 (Pick 18-28)",
      proComp: "George Kirby / Logan Webb",
      summary: "Pinpoint command artist with top-of-the-scale spin metrics. Generates 2840 RPM on an unhittable two-plane sweeper. Walks less than 1.4 batters per nine innings while changing eye levels masterfully.",
      tags: "Elite Command, 2800+ RPM Sweeper, Low Walk Rate, High Floor Starter",
      exitVelocityMax: null,
      sixtyTime: null,
      popTime: null,
      fastballVeloPeak: 95.8,
      fastballVeloSit: 93.2,
      spinRate: 2840,
      hitPresent: 20,
      hitFuture: 20,
      powerPresent: 20,
      powerFuture: 20,
      runPresent: 40,
      runFuture: 40,
      armPresent: 65,
      armFuture: 70,
      fieldPresent: 60,
      fieldFuture: 65,
      fastballPresent: 55,
      fastballFuture: 60,
      sliderPresent: 65,
      sliderFuture: 75,
      curveballPresent: 50,
      curveballFuture: 55,
      changeupPresent: 55,
      changeupFuture: 65,
      commandPresent: 70,
      commandFuture: 75,
      ofpScore: 65,
      reports: {
        create: [
          {
            scoutName: "Mike Callahan (Crosschecker)",
            eventName: "Pac-12 Tournament vs. Stanford",
            summary: "Threw 8 shutout innings with 11 strikeouts and 0 walks. Dotting fastballs to both corners of the plate. Sweeper was unhittable with 16 inches of horizontal sweep.",
            strengths: "Pinpoint command, elite spin rate, tunnel vision delivery, pitch sequencing IQ",
            weaknesses: "Fastball velocity tops out at 96; won't blow batters away with raw heat alone",
            videoUrl: null,
            grade: 65,
          },
        ],
      },
    },
    {
      name: "Braxton 'Buck' O'Connor",
      position: "C",
      secondaryPosition: null,
      bats: "L",
      throws: "R",
      height: "6'1\"",
      weight: 210,
      school: "Harvard-Westlake HS (CA)",
      schoolType: "HIGH_SCHOOL",
      gradYear: 2025,
      status: "COMMITTED",
      commitment: "UCLA",
      draftProjection: "Comp Round A / Round 2",
      proComp: "Adley Rutschman prep comp / Dalton Rushing",
      summary: "Rare left-handed hitting prep catcher with advanced defensive maturity. Clocked a lightning-fast 1.82s pop time during showcase throwing drills. Shows mature receiving instincts and high leadership quotient.",
      tags: "Sub-1.85 Pop Time, Left-Handed Catcher, Elite Leadership, Plus Receiver",
      exitVelocityMax: 104.2,
      sixtyTime: 7.15,
      popTime: 1.82,
      fastballVeloPeak: null,
      fastballVeloSit: null,
      spinRate: null,
      hitPresent: 40,
      hitFuture: 55,
      powerPresent: 45,
      powerFuture: 60,
      runPresent: 35,
      runFuture: 35,
      armPresent: 65,
      armFuture: 70,
      fieldPresent: 55,
      fieldFuture: 65,
      ofpScore: 60,
      reports: {
        create: [
          {
            scoutName: "Mike Callahan (West Coast Crosschecker)",
            eventName: "Borasp Classic (Southern California)",
            summary: "Commanded the pitching staff like a 10-year pro. Picked off a runner at first base with a snap throw from his knees. Compact left-handed stroke with pull-side lift.",
            strengths: "Quick exchange, arm strength, game management, compact swing",
            weaknesses: "Foot speed is limited; needs reps handling professional spin out of the zone",
            videoUrl: null,
            grade: 60,
          },
        ],
      },
    },
    {
      name: "Malik 'The Jet' Washington",
      position: "SS",
      secondaryPosition: "2B",
      bats: "R",
      throws: "R",
      height: "6'1\"",
      weight: 190,
      school: "Parkview High School (GA)",
      schoolType: "HIGH_SCHOOL",
      gradYear: 2025,
      status: "TOP_TARGET",
      commitment: "Tennessee",
      draftProjection: "Top 10 Overall Pick",
      proComp: "CJ Abrams / Anthony Volpe with more arm",
      summary: "Explosive multi-sport prep athlete with twitchy fast-twitch athleticism. Fluid range deep into the hole at shortstop with an absolute rocket for an arm (92 mph across the diamond). High motor player.",
      tags: "Twitchy Athlete, 70 Arm, Plus Range, 5-Tool Ceiling",
      exitVelocityMax: 107.5,
      sixtyTime: 6.44,
      popTime: null,
      fastballVeloPeak: null,
      fastballVeloSit: null,
      spinRate: null,
      hitPresent: 40,
      hitFuture: 60,
      powerPresent: 45,
      powerFuture: 60,
      runPresent: 70,
      runFuture: 65,
      armPresent: 65,
      armFuture: 70,
      fieldPresent: 55,
      fieldFuture: 65,
      ofpScore: 65,
      reports: {
        create: [
          {
            scoutName: "Sam Rodriguez (Southeast Regional)",
            eventName: "Georgia High School 7A State Playoffs",
            summary: "Made two highlight-reel backhand plays into the shortstop hole with jumping throws to first. Singled, stole second, and scored on a wild pitch in the 7th. Electricity in everything he does.",
            strengths: "Fast twitch actions, arm strength, closing speed, high-energy makeup",
            weaknesses: "Can get aggressive early in counts; working on flattening swing against breaking balls",
            videoUrl: null,
            grade: 65,
          },
        ],
      },
    },
    {
      name: "Liam 'The Anchor' Gallagher",
      position: "LHP",
      secondaryPosition: null,
      bats: "L",
      throws: "L",
      height: "6'5\"",
      weight: 235,
      school: "University of Arkansas",
      schoolType: "COLLEGE",
      gradYear: 2025,
      status: "WATCHLIST",
      commitment: "Draft Eligible Junior",
      draftProjection: "Round 2 Target",
      proComp: "Carlos Rodón / Ranger Suárez",
      summary: "Physical SEC southpaw with heavy sinking fastball that generates a 64% groundball rate. Fastball sits 93-96 with vicious arm-side run, paired with an 85 mph hard biting slider.",
      tags: "Heavy Sinker, Groundball Machine, Bullpen / Starter Versatility, High Durability",
      exitVelocityMax: null,
      sixtyTime: null,
      popTime: null,
      fastballVeloPeak: 97.4,
      fastballVeloSit: 94.1,
      spinRate: 2390,
      hitPresent: 20,
      hitFuture: 20,
      powerPresent: 20,
      powerFuture: 20,
      runPresent: 35,
      runFuture: 35,
      armPresent: 70,
      armFuture: 75,
      fieldPresent: 50,
      fieldFuture: 55,
      fastballPresent: 60,
      fastballFuture: 65,
      sliderPresent: 55,
      sliderFuture: 65,
      curveballPresent: 45,
      curveballFuture: 50,
      changeupPresent: 50,
      changeupFuture: 60,
      commandPresent: 50,
      commandFuture: 55,
      ofpScore: 60,
      reports: {
        create: [
          {
            scoutName: "David Vance (National Scouting Director)",
            eventName: "NCAA Super Regional vs. LSU",
            summary: "6 innings of heavy sinkers. Induced 12 groundball outs with 8 strikeouts. Opponents couldn't elevate the ball all afternoon. Durable workhorse build.",
            strengths: "Heavy sink, groundball rate, durable frame, competitiveness",
            weaknesses: "Changeup is a distant third pitch; command can waver when pitching deep into counts",
            videoUrl: null,
            grade: 60,
          },
        ],
      },
    },
  ];

  for (const prospectData of prospects) {
    const p = await prisma.prospect.create({
      data: prospectData,
    });
    console.log(`Created prospect: ${p.name} (${p.position}) - OFP: ${p.ofpScore}`);
  }

  console.log(`\nSuccessfully seeded ${prospects.length} baseball prospects and field reports!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
